server:
  port: 8081
  servlet:
    context-path: /client1
    session:
      cookie:
        name: SSO-CLIENT1-SESSION

auth-server-url: http://oauth.sso.com # 认证服务器后台地址
client-web-url: http://client1-web.sso.com

spring:
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: client1
      client-secret: 123456
      scope: write_bye
      user-authorization-uri: ${auth-server-url}/auth/oauth/authorize # 获取用户的授权码地址
      access-token-uri: ${auth-server-url}/auth/oauth/token # 获取访问令牌的地址
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      user-info-uri: ${auth-server-url}/auth/auth/user
      token-info-uri: ${auth-server-url}/auth/oauth/check_token # 校验访问令牌是否有效的地址
