server:
  port: 9091
  servlet:
    session:
      cookie:
        name: SSO-CLIENT1-SESSIONID # 自定义 Session 的 Cookie 名字，防止冲突。冲突后，会导致 SSO 登陆失败

auth-server: http://127.0.0.1:9090 # 认证服务器地址localhost

security:
  oauth2:
    # OAuth2 Client 配置，对应 OAuth2ClientProperties 类
    client:
      client-id: client1
      client-secret: 123456
      scope: read_hello,write_bye
      user-authorization-uri: ${auth-server}/oauth/authorize # 获取用户的授权码地址
      access-token-uri: ${auth-server}/oauth/token # 获取访问令牌的地址
    # OAuth2 Resource 配置，对应 ResourceServerProperties 类
    resource:
      token-info-uri: ${auth-server}/oauth/check_token # 校验访问令牌是否有效的地址
